---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.0.2
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: true
    checksum: true
    download: true
    fetch: true
    git: false
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: true
app_desc: help manage kubernetes applications
app_name: helm
app_repo: https://github.com/helm/helm
app_type: standalone
app_website: https://helm.sh
archive_conf_path: ''
archive_conf_strip: 1
archive_enabled: true
archive_regex: (\.tar\.gz|\.tgz|\.zip)$
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://get.helm.sh/helm-v{version}-{os}-{arch}.tar.gz.sha256sum
custom_arch_enabled: true
custom_arch_yaml:
    aarch64*: arm64
    armv5*: arm
    armv6*: arm
    armv7*: arm
    i386: '386'
    i686: '386'
    powerpc64le: ppc64le
    ppc64le: ppc64le
    x86: '386'
    x86_64: amd64
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_os_enabled: false
custom_require_commands: ''
download_url: https://get.helm.sh/helm-v{version}-{os}-{arch}.tar.gz
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    helm: bin/helm
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-helm
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-helm.git
source_enabled: false
test_cmd_args: version --short
version_file_enabled: false
version_prefix: v
