---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.1
_src_path: gh:kc-workspace/asdf-plugin-template.git
app_download_file: helm
app_download_link: https://get.helm.sh/helm-v${version}-${os}-${arch}.tar.gz
app_download_type: file
app_git_repo: https://github.com/helm/helm
app_name: helm
app_strip_component: 1
git_remote: https://github.com/kc-workspace/asdf-helm.git
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-helm
plugin_org: kc-workspace
setting_os_mapper_darwin: darwin
setting_os_mapper_linux: linux
settings_os_mapper_enabled: false
