---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.3-23-g4e38462
_src_path: .
app_description: help manage kubernetes applications
app_name: helm
app_repo: https://github.com/helm/helm
app_version_prefix: v
app_website: https://helm.sh
custom_arch_enabled: true
custom_arch_yaml:
    aarch64*: arm64
    armv5*: arm
    armv6*: arm
    armv7*: arm
    i386: 386
    i686: 386
    powerpc64le: ppc64le
    ppc64le: ppc64le
    x86: 386
    x86_64: amd64
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_os_enabled: false
download_checksum_cmd: '256'
download_checksum_enabled: true
download_checksum_link: https://get.helm.sh/helm-v{version}-{os}-{arch}.tar.gz.sha256sum
download_link: https://get.helm.sh/helm-v{version}-{os}-{arch}.tar.gz
download_location: helm
download_strip: 1
download_type: archive-file
install_type: single-file
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-helm
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-helm
test_cmd_args: ''
